### ISSUE TITLE
Fails to find files

### ISSUE THREAD

**Issue by happycollision** [derrekyoung/ScriptsAndUtils#1]
The code seems to be missing two quotes that keep unix from being able to find the files. I am new to GitHub (and Git (... and working in Terminal) ) so I am not sure of the best way to make a code suggestion. But changing line 47 from

``` shell
find "$i" -name *.$input_file_type | while read in_file
```

to

``` shell
find "$i" -name "*.$input_file_type" | while read in_file
```

fixes the issue I was having.

**Comment by derrekyoung** [comment]
Interesting. It runs fine on my Mac. What OS are you using?

**Comment by happycollision** [comment]
Mountain Lion. I am very new to anything involving the terminal but I've been coding PHP for a few years. So I just kind of guessed at adding the quotes after trying to do a million other things and then, boom, it worked. Someone else who got the script from your website (not github) wrote the same thing in your comments.  Strange. It obviously works for some people out of the box, but others need the quotes.

I have a theory that I haven't tested yet: It might behave differently depending on how you call it. `bash script.sh` vs `sh script.sh`

I am guessing that they each interpret things slightly differently, but I really don't know anything about it.

Thanks so much for the script! I am combining it with another script that exports three different versions of each video so that you get an HTML5 compliant set of video files all sitting in the same directory with the same name. I'll push it out to my github when I am done if you are interested.

~Don
